# Site settings
title: > 
  Hi! I'm Derek
email: derekasuzumoto@gmail.com
url: https://shigi3333.github.io
description: >- 
  Hi! My name is Derek Suzumoto. I am a young software developer in the making!
  I have a Bachelors of Science in Computer Science from Colorado School of
  Mines. I am Solution-oriented, and always looking to develop new industry
  skills. I think of myself as adept at creative problem solving, and draw on a
  large knowledge bank of experience in other fields I've worked in to find 
  novel solutions. This website is here to give you a good idea of who I am,
  and show off some of my work! Thanks for taking a look!
keywords: >- 
  HTML, CSS, JavaScript, Java, Python, C++, AGILE, Scrum, Leadership, Teamwork,
  SolidWORKS, VS Code, Test Driven Design, Microcontrollers, Raspberry Pi,
  Postgres, MySQL, XAMPP, Apache, OpenCV, SCiKit Learn, Keras, Tensorflow, PHP,
  AJAX, JQuery, Ruby, R, BASH, Ocaml, Developer, Resume, Portfolio, Profile,
  Engineer, Programmer, Software.
skills: "Web Dev - Computer Vision - Database - AGILE"
meta_author: Suzumoto Derek

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Formspree Endpoint for contact submission form
contact_endpoint: "//formspree.io/f/xrbykwwn"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CEB7D7
  primary-rgb: "255,255,255"
  secondary: 81987F
  secondary-dark: ACC9AD

# Footer settings
footer:
  copyright: Derek Suzumoto
  location: Located In
  social: Find Me On
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/Shigi3333
  - title: linkedin
    url: https://www.linkedin.com/in/dsuzumoto/
  - title: indeed
    url: https://profile.indeed.com/p/dereks-hftm1tg

# Postal address (add as many lines as necessary)
address:
  - line: Denver, Colorado

# Credits content
credits: 'Freelancer Jekyll Template by Jerome Lachaud'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
