# Site settings
title: > 
  Hi! I'm Derek
email: derekasuzumoto@gmail.com
url: https://shigi3333.github.io
description: >- 
  Hi! My name is Derek Suzumoto. I am a young software developer in the making!
  I have a Bachelors of Science in Computer Science from Colorado School of
  Mines. I am Solution-oriented, and always looking to develop new industry
  skills. I think of myself as adept at creative problem solving, and draw on a
  large knowledge bank of experience in other fields I've worked in to find 
  novel solutions. This website is here to give you a good idea of who I am,
  and show off some of my work! Thanks for taking a look!
keywords: >- 
  Agile, Web Hosting, Software Documentation, Client Relations, Product
  Deployment, JavaScript Libraries, React, React.js, Flask, New Business
  Development, Jira, Project Management, Computer Vision, OpenCV, SCRUM, Image
  Editing, Linux, Java, Python, Web Development, C++, Raspberry PI, Developer,
  Resume, Portfolio, Profile, Engineer, Programmer, Software, Tech, Startup,
  Disruptor, TypeScript, Bootstrap, Liquid, Jekyll, HTML5, CSS3, Postgres,
  MySQL, SQL, Database, Unix, BASH, Git, Github, Azure, Arduino, Docker
skills: "Web Dev - Computer Vision - Technical Communication - AGILE"
meta_author: Suzumoto Derek

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Formspree Endpoint for contact submission form
contact_endpoint: "//formspree.io/f/xrbykwwn"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CEB7D7
  primary-rgb: "255,255,255"
  secondary: 81987F
  secondary-dark: ACC9AD

# Footer settings
footer:
  copyright: Derek Suzumoto
  location: Located In
  social: Find Me On
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/Shigi3333
  - title: linkedin
    url: https://www.linkedin.com/in/dsuzumoto/
  - title: indeed
    url: https://profile.indeed.com/p/dereks-hftm1tg

# Postal address (add as many lines as necessary)
address:
  - line: Denver, Colorado

# Credits content
credits: >- 
  Freelancer Jekyll Template by Jerome Lachaud<br>Icons from: <br><a
  href="https://devicon.dev/" target="_blank" style="color: inherit;">Devicon</a>
  <br><a href="https://fontawesome.com/" target="_blank" style="color:
  inherit;">FontAwesome</a>
  <br><a href="https://www.coreui.io/icons/" target="_blank" style="color: inherit;">CoreUI Icons</a>
  <br><a href="https://www.flaticon.com/" target="_blank" style="color: inherit;">Flaticon authors Flat Icons, juicy_fish, Awicon,
  Canticons, Freepik, kliwir art, Parzival 1997, zero_wing, and Vectors Market. </a>

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
